name: Flet Build APK

on:
  push:
    branches: [ main ]
  workflow_dispatch: # Allows you to run it manually

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java (Required for Android)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Flet CLI
        run: |
          pip install "flet[all]" yt-dlp

      - name: Build APK
        run: |
          # The -v flag gives you a detailed log if things go wrong
          flet build apk -v

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Carl-YDL-App
          path: build/apk/*.apk
